"""
BagBuddy Brand ROI Calculator

This module calculates ROI metrics for brands on the BagBuddy platform.

Business Model Assumptions:
- Cost per bag slot: $0.20 (what each brand pays)
- Ad slots per bag: 8 brands
- Distribution: 5,000 bags per quarter (3 months)
- Ad reward: User gets points for watching 10-second ad
- Campaign duration: Minimum 1 quarter (can run multiple quarters)
- QR code redemption: Brand-specific, generated by user
"""

from typing import Dict, Any


class BrandROICalculator:
    """Calculate ROI metrics for BagBuddy brand campaigns."""
    
    # Platform constants
    COST_PER_BAG_SLOT = 0.15  # $0.15 per bag slot (what brand pays)
    AD_SLOTS_PER_BAG = 8  # 8 brand slots per bag
    BAGS_PER_QUARTER = 5000  # 5,000 bags distributed per quarter
    
    def __init__(self, campaign_data: Dict[str, Any]):
        """
        Initialize the ROI calculator with campaign data.
        
        Args:
            campaign_data: Dictionary containing campaign metrics
                Required keys:
                - num_quarters: Number of quarters campaign runs (minimum 1)
                - scan_rate: Percentage of bags that get scanned (0-100)
                - conversion_rate: Percentage of scans that convert (0-100)
                - avg_revenue_per_conversion: Average sales value per conversion
                - impressions_per_bag: Average physical views per bag
                - trees_planted: Optional environmental impact metric
        """
        self.campaign_data = campaign_data
    
    def calculate_campaign_cost(self) -> float:
        """
        Calculate total amount paid by the brand for ad placement.
        
        Formula: Cost per Bag Slot × Total Bags Distributed
        
        Returns:
            Campaign cost in dollars
        """
        num_quarters = self.campaign_data.get('num_quarters', 1)
        total_bags = self.BAGS_PER_QUARTER * num_quarters
        
        campaign_cost = self.COST_PER_BAG_SLOT * total_bags
        return round(campaign_cost, 2)
    
    def calculate_num_bags_distributed(self) -> int:
        """
        Calculate total bags in circulation carrying the brand's ad.
        
        Returns:
            Total number of bags distributed
        """
        num_quarters = self.campaign_data.get('num_quarters', 1)
        return self.BAGS_PER_QUARTER * num_quarters
    
    def get_ad_slots_per_bag(self) -> int:
        """
        Get number of different brand ads printed on each bag.
        
        Returns:
            Number of ad slots per bag (constant: 8)
        """
        return self.AD_SLOTS_PER_BAG
    
    def calculate_cost_per_bag_slot(self) -> float:
        """
        Calculate price paid by the brand for one ad placement on a single bag.
        
        Returns:
            Cost per bag slot in dollars (constant: $0.20)
        """
        return self.COST_PER_BAG_SLOT
    
    def calculate_total_impressions(self) -> int:
        """
        Calculate total number of times the ad is seen (physical + digital).
        
        Physical impressions = Bags × Impressions per Bag
        Digital impressions = Scans (each scan = 1 digital view)
        
        Returns:
            Total impressions
        """
        bags_distributed = self.calculate_num_bags_distributed()
        impressions_per_bag = self.campaign_data.get('impressions_per_bag', 10)
        
        # Physical impressions (people seeing the bag)
        physical_impressions = bags_distributed * impressions_per_bag
        
        # Digital impressions (QR scans)
        digital_impressions = self.calculate_engagements_scans()
        
        total_impressions = physical_impressions + digital_impressions
        return total_impressions
    
    def calculate_impressions_per_bag(self) -> float:
        """
        Calculate average number of views each bag generates.
        
        Returns:
            Impressions per bag
        """
        total_impressions = self.calculate_total_impressions()
        bags_distributed = self.calculate_num_bags_distributed()
        
        if bags_distributed == 0:
            return 0.0
        
        impressions_per_bag = total_impressions / bags_distributed
        return round(impressions_per_bag, 2)
    
    def calculate_scan_rate(self) -> float:
        """
        Calculate percentage of people who scan the QR code.
        
        Returns:
            Scan rate as a percentage
        """
        scan_rate = self.campaign_data.get('scan_rate', 0)
        return round(scan_rate, 2)
    
    def calculate_engagements_scans(self) -> int:
        """
        Calculate total number of QR scans or interactions on the BagBuddy app.
        
        Formula: Bags Distributed × (Scan Rate / 100)
        
        Returns:
            Total number of scans
        """
        bags_distributed = self.calculate_num_bags_distributed()
        scan_rate = self.campaign_data.get('scan_rate', 0) / 100
        
        scans = int(bags_distributed * scan_rate)
        return scans
    
    def calculate_conversion_rate(self) -> float:
        """
        Calculate percentage of engaged users who redeem or take action.
        
        Returns:
            Conversion rate as a percentage
        """
        conversion_rate = self.campaign_data.get('conversion_rate', 0)
        return round(conversion_rate, 2)
    
    def calculate_conversions_redemptions(self) -> int:
        """
        Calculate actual number of users who redeemed an offer or purchased.
        
        Formula: Scans × (Conversion Rate / 100)
        
        Returns:
            Total conversions/redemptions
        """
        scans = self.calculate_engagements_scans()
        conversion_rate = self.campaign_data.get('conversion_rate', 0) / 100
        
        conversions = int(scans * conversion_rate)
        return conversions
    
    def calculate_avg_revenue_per_conversion(self) -> float:
        """
        Get estimated sales value generated from each redemption.
        
        Returns:
            Average revenue per conversion in dollars
        """
        avg_revenue = self.campaign_data.get('avg_revenue_per_conversion', 0)
        return round(avg_revenue, 2)
    
    def calculate_total_sales_generated(self) -> float:
        """
        Calculate overall revenue attributed to the campaign.
        
        Formula: Conversions × Avg Revenue per Conversion
        
        Returns:
            Total sales in dollars
        """
        conversions = self.calculate_conversions_redemptions()
        avg_revenue = self.calculate_avg_revenue_per_conversion()
        
        total_sales = conversions * avg_revenue
        return round(total_sales, 2)
    
    def calculate_roi(self) -> float:
        """
        Calculate Return on Investment percentage.
        
        Formula: ((Total Sales - Campaign Cost) / Campaign Cost) × 100
        
        Returns:
            ROI as a percentage
        """
        total_sales = self.calculate_total_sales_generated()
        campaign_cost = self.calculate_campaign_cost()
        
        if campaign_cost == 0:
            return 0.0
        
        roi = ((total_sales - campaign_cost) / campaign_cost) * 100
        return round(roi, 2)
    
    def calculate_cost_per_impression(self) -> float:
        """
        Calculate Cost per Impression (CPI).
        
        Formula: Campaign Cost / Total Impressions
        
        Returns:
            CPI in dollars
        """
        campaign_cost = self.calculate_campaign_cost()
        total_impressions = self.calculate_total_impressions()
        
        if total_impressions == 0:
            return 0.0
        
        cpi = campaign_cost / total_impressions
        return round(cpi, 4)
    
    def calculate_cost_per_engagement(self) -> float:
        """
        Calculate Cost per Engagement (CPE).
        
        Formula: Campaign Cost / Engagements (Scans)
        
        Returns:
            CPE in dollars
        """
        campaign_cost = self.calculate_campaign_cost()
        scans = self.calculate_engagements_scans()
        
        if scans == 0:
            return 0.0
        
        cpe = campaign_cost / scans
        return round(cpe, 4)
    
    def calculate_cost_per_conversion(self) -> float:
        """
        Calculate Cost per Acquisition/Conversion (CPA).
        
        Formula: Campaign Cost / Conversions
        
        Returns:
            CPA in dollars
        """
        campaign_cost = self.calculate_campaign_cost()
        conversions = self.calculate_conversions_redemptions()
        
        if conversions == 0:
            return 0.0
        
        cpa = campaign_cost / conversions
        return round(cpa, 2)
    
    def calculate_environmental_impact(self) -> Dict[str, Any]:
        """
        Calculate environmental impact metrics.
        
        Returns:
            Dictionary with environmental metrics
        """
        trees_planted = self.campaign_data.get('trees_planted', 0)
        bags_distributed = self.calculate_num_bags_distributed()
        
        # Each reusable bag can replace ~500 single-use plastic bags
        plastic_bags_saved = bags_distributed * 500
        
        # Carbon offset estimate (kg CO2)
        # Assume each reusable bag saves ~5kg CO2 over its lifetime
        carbon_offset_kg = bags_distributed * 5
        
        return {
            'trees_planted': trees_planted,
            'plastic_bags_saved': plastic_bags_saved,
            'carbon_offset_kg': carbon_offset_kg,
            'eco_points': trees_planted * 100  # 100 eco-points per tree
        }
    
    def get_full_report(self) -> Dict[str, Any]:
        """
        Generate a comprehensive ROI report for BagBuddy campaigns.
        
        Returns:
            Dictionary with all calculated metrics
        """
        env_impact = self.calculate_environmental_impact()
        
        return {
            # Campaign Basics
            'campaign_cost': self.calculate_campaign_cost(),
            'num_bags_distributed': self.calculate_num_bags_distributed(),
            'ad_slots_per_bag': self.get_ad_slots_per_bag(),
            'cost_per_bag_slot': self.calculate_cost_per_bag_slot(),
            
            # Impressions & Engagement
            'total_impressions': self.calculate_total_impressions(),
            'impressions_per_bag': self.calculate_impressions_per_bag(),
            'scan_rate_percent': self.calculate_scan_rate(),
            'engagements_scans': self.calculate_engagements_scans(),
            
            # Conversions & Revenue
            'conversion_rate_percent': self.calculate_conversion_rate(),
            'conversions_redemptions': self.calculate_conversions_redemptions(),
            'avg_revenue_per_conversion': self.calculate_avg_revenue_per_conversion(),
            'total_sales_generated': self.calculate_total_sales_generated(),
            
            # ROI & Cost Metrics
            'roi_percent': self.calculate_roi(),
            'cost_per_impression': self.calculate_cost_per_impression(),
            'cost_per_engagement': self.calculate_cost_per_engagement(),
            'cost_per_conversion': self.calculate_cost_per_conversion(),
            
            # Environmental Impact
            'environmental_impact': env_impact,
            
            # Input Parameters (for reference)
            'num_quarters': self.campaign_data.get('num_quarters', 1)
        }


if __name__ == "__main__":
    # Example usage - BagBuddy Campaign
    sample_campaign = {
        'campaign_name': 'Coffee Shop Q1 2025',
        'num_quarters': 1,  # 1 quarter = 5,000 bags
        'scan_rate': 2,  # 2% scan rate (realistic based on QR code industry benchmarks)
        'conversion_rate': 20,  # 20% of scans result in redemption
        'avg_revenue_per_conversion': 25,  # $25 average purchase per redemption
        'impressions_per_bag': 5,  # Realistic: Each bag generates ~5 brand-specific impressions
                                    # (8 brands per bag, people notice 1-2 brands per view)
        'trees_planted': 100  # Brand plants 100 trees as part of campaign
    }
    
    calculator = BrandROICalculator(sample_campaign)
    report = calculator.get_full_report()
    
    # Calculate components for detailed breakdown
    bags_distributed = calculator.calculate_num_bags_distributed()
    impressions_per_bag = sample_campaign['impressions_per_bag']
    physical_impressions = bags_distributed * impressions_per_bag
    digital_impressions = calculator.calculate_engagements_scans()
    
    print("\n" + "=" * 80)
    print(f"BAGBUDDY BRAND ROI REPORT: {sample_campaign['campaign_name']}")
    print("=" * 80 + "\n")
    
    print("CAMPAIGN COST BREAKDOWN")
    print("-" * 80)
    print(f"Campaign Cost: ${report['campaign_cost']:,.2f}")
    print(f"Number of Bags Distributed: {report['num_bags_distributed']:,}")
    print(f"Ad Slots per Bag: {report['ad_slots_per_bag']}")
    print(f"Cost per Bag Slot: ${report['cost_per_bag_slot']:.4f}\n")
    
    print("IMPRESSIONS & ENGAGEMENT (DETAILED BREAKDOWN)")
    print("-" * 80)
    print(f"Physical Impressions:")
    print(f"  Bags Distributed: {bags_distributed:,}")
    print(f"  × Impressions per Bag: {impressions_per_bag}")
    print(f"  = Physical Impressions: {physical_impressions:,}\n")
    
    print(f"Digital Impressions:")
    print(f"  QR Code Scans: {digital_impressions:,}\n")
    
    print(f"Total Impressions: {report['total_impressions']:,}")
    print(f"  (Physical: {physical_impressions:,} + Digital: {digital_impressions:,})\n")
    
    print(f"Impressions per Bag: {report['impressions_per_bag']:,.2f}")
    print(f"Scan Rate: {report['scan_rate_percent']}%")
    print(f"Total Scans/Engagements: {report['engagements_scans']:,}\n")
    
    print("CONVERSIONS & REVENUE")
    print("-" * 80)
    print(f"Conversion Rate: {report['conversion_rate_percent']}%")
    print(f"Total Conversions/Redemptions: {report['conversions_redemptions']:,}")
    print(f"Average Revenue per Conversion: ${report['avg_revenue_per_conversion']:,.2f}")
    print(f"Total Sales Generated: ${report['total_sales_generated']:,.2f}\n")
    
    print("ROI & COST METRICS")
    print("-" * 80)
    print(f"ROI: {report['roi_percent']}%")
    print(f"Cost per Impression (CPI): ${report['cost_per_impression']:.4f}")
    print(f"Cost per Engagement (CPE): ${report['cost_per_engagement']:.4f}")
    print(f"Cost per Conversion (CPA): ${report['cost_per_conversion']:.2f}\n")
    
    print("ENVIRONMENTAL IMPACT")
    print("-" * 80)
    env = report['environmental_impact']
    print(f"Trees Planted: {env['trees_planted']:,}")
    print(f"Plastic Bags Saved: {env['plastic_bags_saved']:,}")
    print(f"Carbon Offset: {env['carbon_offset_kg']:,} kg CO2")
    print(f"Eco-Points Earned: {env['eco_points']:,}\n")
    
    print("=" * 80)
    print(f"\n💡 Campaign Summary:")
    print(f"   For an investment of ${report['campaign_cost']:,.2f}, the brand generated")
    print(f"   ${report['total_sales_generated']:,.2f} in sales, achieving a {report['roi_percent']}% ROI.")
    print(f"   The campaign reached {report['total_impressions']:,} impressions across")
    print(f"   {report['num_bags_distributed']:,} BagBuddy bags.\n")
    print("=" * 80)
